name: Draggable Navball
urls:
  ckan_ver:  https://github.com/andrew-vant/dragnav/releases/latest/download/ckan.version.json
  releases:  https://github.com/andrew-vant/dragnav/releases
  changelog: https://raw.githubusercontent.com/andrew-vant/dragnav/master/CHANGES.md
ksp:
  version:     1.8.1
  version_min: 1.8.0
  version_max: null
